// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Chat(arg1:Array<main.ChatMessage>,arg2:string):Promise<main.ChatResponse>;

export function ClearSession():Promise<void>;

export function GetAPIBaseURL():Promise<string>;

export function GetDefaultClientID():Promise<string>;

export function GetDefaultLLMModel():Promise<string>;

export function GetSession():Promise<main.SessionState>;

export function IsWailsRuntime():Promise<boolean>;

export function LoadChatConversations():Promise<Array<main.ChatConversation>>;

export function Login(arg1:string,arg2:string,arg3:boolean):Promise<main.OpenTokenResponse>;

export function LoginByEmailCode(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.OpenTokenResponse>;

export function Logout():Promise<main.MessageResponse>;

export function RefreshSession(arg1:string):Promise<main.OpenTokenResponse>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.OpenRegisterResponse>;

export function RegisterByEmail(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.BaseResponse>;

export function RestoreSession():Promise<main.OpenTokenResponse>;

export function SaveChatConversations(arg1:Array<main.ChatConversation>):Promise<void>;

export function SendEmailCode(arg1:string,arg2:string):Promise<main.BaseResponse>;

export function StartChatStream(arg1:string,arg2:Array<main.ChatMessage>,arg3:string):Promise<void>;

export function StopChatStream(arg1:string):Promise<void>;
