// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function GetAPIBaseURL() {
  return window['go']['main']['App']['GetAPIBaseURL']();
}

export function GetDefaultClientID() {
  return window['go']['main']['App']['GetDefaultClientID']();
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function IsWailsRuntime() {
  return window['go']['main']['App']['IsWailsRuntime']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function LoginByEmailCode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LoginByEmailCode'](arg1, arg2, arg3, arg4);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RefreshSession(arg1) {
  return window['go']['main']['App']['RefreshSession'](arg1);
}

export function Register(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4, arg5);
}

export function RegisterByEmail(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RegisterByEmail'](arg1, arg2, arg3, arg4);
}

export function RestoreSession() {
  return window['go']['main']['App']['RestoreSession']();
}

export function SendEmailCode(arg1, arg2) {
  return window['go']['main']['App']['SendEmailCode'](arg1, arg2);
}
