// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearSession():Promise<void>;

export function GetAPIBaseURL():Promise<string>;

export function GetDefaultClientID():Promise<string>;

export function GetSession():Promise<main.SessionState>;

export function IsWailsRuntime():Promise<boolean>;

export function Login(arg1:string,arg2:string,arg3:boolean):Promise<main.OpenTokenResponse>;

export function LoginByEmailCode(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.OpenTokenResponse>;

export function Logout():Promise<main.MessageResponse>;

export function RefreshSession(arg1:string):Promise<main.OpenTokenResponse>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.OpenRegisterResponse>;

export function RegisterByEmail(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.BaseResponse>;

export function RestoreSession():Promise<main.OpenTokenResponse>;

export function SendEmailCode(arg1:string,arg2:string):Promise<main.BaseResponse>;
